# Generated by Django 3.2 on 2021-04-27 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('full_text', models.TextField(verbose_name='Описание')),
                ('priority', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1)),
            ],
        ),
    ]
